### ISSUE TITLE
Why do servers often kick me out?

### ISSUE THREAD

**Issue by q848899** [CattaLol/Faster-Petrax#1]
Irregular timing
use this mod, you'll drop the line, won't you?

**Comment by CattaLol** [comment]
Servers are probably kicking you out because it thinks you're speed/teleport hacking (let's be honest, if you're using this mod you effectively are). I'd suggest hooking S_EXIT and printing out the code/category - if it's code 0 category 16, then that's the reason why.

You can alleviate the issue to some degree by not moving excessively after the teleportation for a few seconds (modify the set coordinates of PETRAX_SPAWN_LOC_BACK and/or PETRAX_SPAWN_LOC_FRONT as needed).

**Comment by CattaLol** [comment]
Servers may be kicking you out because it thinks you're speed/teleport hacking (if you're using this mod you effectively are). You can confirm this by hooking S_EXIT and printing out the code/category: auto-kick for what it thinks is speed-hacking is code 0 category 16.

If the above is indeed the case, you can alleviate the issue to some degree by not moving excessively after the teleportation for a few seconds (modify the set coordinates of PETRAX_SPAWN_LOC_BACK and/or PETRAX_SPAWN_LOC_FRONT as needed).

**Comment by CattaLol** [comment]
Servers may be kicking you out because it thinks you're speed/teleport hacking (if you're using this mod you effectively are). 

If the above is indeed the case, you can alleviate the issue to some degree by not moving excessively after the teleportation for a few seconds (modify the set coordinates of PETRAX_SPAWN_LOC_BACK and/or PETRAX_SPAWN_LOC_FRONT as needed).

It is difficult to say for certain, as other mods ~~or exploits~~ may be also generating actions that cause the server to auto-kick you.

**Comment by CattaLol** [comment]
Servers may be kicking you out because it thinks you're excessively speed/teleport hacking (if you're using this mod you effectively are).

If the above is indeed the case, you can alleviate the issue to some degree by not moving excessively after the teleportation for a few seconds (modify the set coordinates of PETRAX_SPAWN_LOC_BACK and/or PETRAX_SPAWN_LOC_FRONT as needed).

It is difficult to say for certain, as other mods or exploits may be also generating actions that cause the server to auto-kick you.

**Comment by CattaLol** [comment]
Servers may be kicking you out because it thinks you're speed/teleport hacking (if you're using this mod you effectively are) for a prolonged period of time.

If the above is indeed the case, you can alleviate the issue to some degree by not moving excessively after the teleportation for a few seconds (modify the set coordinates of PETRAX_SPAWN_LOC_BACK and/or PETRAX_SPAWN_LOC_FRONT as needed).

It is difficult to say for certain, as other mods or exploits may be also generating actions that cause the server to auto-kick you.

**Comment by CattaLol** [comment]
Servers may be kicking you out because it thinks you're speed/teleport hacking (if you're using this mod you effectively are) for a period of time.

If the above is indeed the case, you can alleviate the issue (to a degree) by not excessively moving after the teleportation for a few seconds (modify the set coordinates of PETRAX_SPAWN_LOC_BACK and/or PETRAX_SPAWN_LOC_FRONT as needed if you need to begin the initial fight in a more comfortable position instead).

It is difficult to say for certain, as other mods or exploits may be also generating actions that cause the server to auto-kick you.

**Comment by CattaLol** [comment]
Servers may be kicking you out because it thinks you're speed/teleport hacking (if you're using this mod you effectively are) for a period of time.

If the above is indeed the case, you can alleviate the issue (to a degree) by not excessively moving after the teleportation for a few seconds (modify the set coordinates of PETRAX_SPAWN_LOC_BACK and/or PETRAX_SPAWN_LOC_FRONT as needed if you need to begin the initial fight in a more comfortable position instead).

Ultimately, it is difficult to say for certain what is causing your server kick, as other mods or exploits may be also generating actions that cause the server to auto-kick you, and/or combined with an excessive amount of lag and/or packet loss.
